### ISSUE TITLE
Set up image (Unsplash) API module

### ISSUE THREAD

**Issue by natalie-pratt** [technomooney/capstone_group_3_project_3#10]
Set up the file (unsplash.py) containing the API call for images that will be at the top of the web app page.

**Comment by oscar-chiqui** [comment]
import os
import requests

UNSPLASH_API_URL = 'https://api.unsplash.com/photos/random'
UNSPLASH_ACCESS_KEY = os.environ.get('UNSPLASH_ACCESS_KEY')

def get_random_image():
    headers = {'Authorization': f'Client-ID {UNSPLASH_ACCESS_KEY}'}
    params = {'query': 'nature', 'orientation': 'landscape'}
    response = requests.get(UNSPLASH_API_URL, headers=headers, params=params)
    if response.status_code == 200:
        return response.json()['urls']['regular']
    else:
        return None


// https://unsplash.com/documentation
// When using Unsplash we make a request to use images in our project. What is your idea for this part of the code, can you please explain it to me?

// The code above is a reference you can use it or not but obviously, I need details,  I know this is assigned to Natalie-Pratt but I wanted to give feedback on this issue for the project.

**Comment by natalie-pratt** [comment]
@oscar-chiqui 

`import requests
import os

base_url = 'https://api.unsplash.com/search/photos?'
key = os.environ.get('UNSPLASH_KEY')


def get_image_response():
    try:
        query = {'query': 'national parks', 'page': 1, 'per_page': 10, 'orientation': 'landscape', 'client_id': key}
        response = requests.get(base_url, params=query)
        response.raise_for_status()
        data = response.json()
        return data, None
    except Exception as ex:
        print(ex) # TODO - Switch to log instead of print
        return None, ex
`

This is the code I currently have for my Unsplash api file.

**Comment by natalie-pratt** [comment]
@oscar-chiqui It will get a response containing 10 random images that I think could be used in a carousel for the top of our page. It doesn't do any processing of data or anything. I'm not positive but I'm pretty sure all it should do is get the response and either return the data or the error message if there is one. Hope this helps!

**Comment by natalie-pratt** [comment]
Issue resolved. Unsplash API is set up.
